# Generated by Django 4.0.5 on 2022-06-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etiqueta_titulo',
            field=models.CharField(default='Publicación', max_length=255),
        ),
    ]
