# Generated by Django 4.0.5 on 2022-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vista',
            field=models.CharField(default='Abre el link de arriba para leer la publicación', max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
