# Generated by Django 4.0.5 on 2022-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_vista_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vista',
            field=models.CharField(default='Escribe un pequeño resúmen', max_length=255),
        ),
    ]
