# Generated by Django 4.0.4 on 2022-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vista',
            field=models.CharField(max_length=255),
        ),
    ]
