# Generated by Django 4.0.5 on 2022-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_de_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
